### ISSUE TITLE
Question about the direction of the project

### ISSUE THREAD

**Issue by tinohager** [ljchuello/Hetzner-Cloud-DotNet#1]
Hello I'm just looking for a package for Hetzner while I noticed that there are 2 active packages here. I just wanted to ask if you know about each other. I myself have written a nuget package for the hetzner dns management.

If you want to place your project as an alternative you can also register here.
https://github.com/hetznercloud/awesome-hcloud

- [hetzner-cloud-api-net](https://github.com/lk-code/hetzner-cloud-api-net)

**Comment by ljchuello** [comment]
Hello!.

No, I don't know the person mentioned, but I have seen his library, it seems very good and it inspired me to make my own, I am currently in a project, where I need to customize a little more. That is why my intention is to create a new project, and take advantage of better documentation to help those who need it.

I will listen to his recommendation, and I integrated my project to https://github.com/hetznercloud/awesome-hcloud

Thank you!.
